### ISSUE TITLE
The problem with running training on windows

### ISSUE THREAD

**Issue by Vubni** [bene-ges/nemo_compatible#17]
The problem with running training on windows. The following error appears, although `pytorch-lightning` is installed

```
PS E:\g++\синтез новый> sh train.sh
train.sh: line 1: ﻿#!/bin/bash: No such file or directory
train.sh: line 2: conda: command not found
fatal: destination path 'ru_g2p_ipa_bert_large' already exists and is not an empty directory.
Traceback (most recent call last):
  File "NeMo/examples/nlp/text_normalization_as_tagging/normalization_as_tagging_infer.py", line 42, in <module>
    from helpers import ITN_MODEL, instantiate_model_and_trainer
  File "E:\g++\синтез новый\NeMo\examples\nlp\text_normalization_as_tagging\helpers.py", line 22, in <module>
    from nemo.collections.nlp.models import ThutmoseTaggerModel
  File "C:\Users\egora\AppData\Local\Programs\Python\Python38\lib\site-packages\nemo\collections\nlp\__init__.py", line 15, in <module>
    from nemo.collections.nlp import data, losses, models, modules
  File "C:\Users\egora\AppData\Local\Programs\Python\Python38\lib\site-packages\nemo\collections\nlp\data\__init__.py", line 42, in <module>
    from nemo.collections.nlp.data.zero_shot_intent_recognition.zero_shot_intent_dataset import (
  File "C:\Users\egora\AppData\Local\Programs\Python\Python38\lib\site-packages\nemo\collections\nlp\data\zero_shot_intent_recognition\__init__.py", line 16, in <module>
    from nemo.collections.nlp.data.zero_shot_intent_recognition.zero_shot_intent_dataset import (
  File "C:\Users\egora\AppData\Local\Programs\Python\Python38\lib\site-packages\nemo\collections\nlp\data\zero_shot_intent_recognition\zero_shot_intent_dataset.py", line 30, in <module>
    from nemo.collections.nlp.parts.utils_funcs import tensor2list
  File "C:\Users\egora\AppData\Local\Programs\Python\Python38\lib\site-packages\nemo\collections\nlp\parts\__init__.py", line 17, in <module>
    from nemo.collections.nlp.parts.utils_funcs import list2str, tensor2list
  File "C:\Users\egora\AppData\Local\Programs\Python\Python38\lib\site-packages\nemo\collections\nlp\parts\utils_funcs.py", line 28, in <module>
    from nemo.collections.nlp.modules.common.megatron.utils import erf_gelu
  File "C:\Users\egora\AppData\Local\Programs\Python\Python38\lib\site-packages\nemo\collections\nlp\modules\__init__.py", line 16, in <module>
    from nemo.collections.nlp.modules.common import (
  File "C:\Users\egora\AppData\Local\Programs\Python\Python38\lib\site-packages\nemo\collections\nlp\modules\common\__init__.py", line 36, in <module>
    from nemo.collections.nlp.modules.common.tokenizer_utils import get_tokenizer, get_tokenizer_list
  File "C:\Users\egora\AppData\Local\Programs\Python\Python38\lib\site-packages\nemo\collections\nlp\modules\common\tokenizer_utils.py", line 29, in <module>
    from nemo.collections.nlp.parts.nlp_overrides import HAVE_MEGATRON_CORE
  File "C:\Users\egora\AppData\Local\Programs\Python\Python38\lib\site-packages\nemo\collections\nlp\parts\nlp_overrides.py", line 31, in <module>
    from pytorch_lightning.overrides.base import _LightningModuleWrapperBase
ModuleNotFoundError: No module named 'pytorch_lightning.overrides.base'
```

**Comment by Vubni** [comment]
Помогло установка нужной версии из https://github.com/NVIDIA/NeMo/blob/main/requirements/requirements_lightning.txt
